import GameDetails from "./components/GameDetails";
import Players from "./components/Players";

import RunningScore from "./components/RunningScore";
import Scores from "./components/Scores";
import ScoresheetHeader from "./components/ScoresheetHeader";
import Signatures from "./components/Signatures";
import TeamStats from "./components/TeamStats";

export default function App() {
  const gameDetails = {
    teamA: "BC MIES",
    teamB: "CATBASKET",
    competition: "BASCUP 2022",
    date: "15.06.23",
    time: "20:30",
    crewChief: "KOTLEBA, L (SVK)",
    gameNo: 169,
    place: "FIBA ARENA, GENEVE",
    umpire1: "JUNGBRAND, C (FIN)",
    umpire2: "RIGASO, G (GRE)",
  };

  const team1Details = {
    timeOuts: [
      {
        H1: [
          [2, "Q2"],
          [8, "Q4"],
        ],
      },
      {
        H2: [
          [9, "Q3"],
          [10, "Q2"],
          [10, "Q4"],
        ],
      },
      {
        OT: [
          [false, false],
          [false, false],
          [false, false],
        ],
      },
    ],
    teamFouls: [
      { Q1: [true, true, true, false] },
      { Q2: [true, true, true, false] },
      { Q3: [true, true, true, true] },
      { Q4: [true, true, true, true] },
    ],
    HCC: ["Q3", 5],
  };

  const team2Details = {
    timeOuts: [
      {
        H1: [
          [5, "Q2"],
          [false, "Q2"],
        ],
      },
      {
        H2: [
          [5, "Q3"],
          [6, "Q2"],
          [10, "Q4"],
        ],
      },
      {
        OT: [
          [false, false],
          [false, false],
          [false, false],
        ],
      },
    ],
    teamFouls: [
      { Q1: [true, true, true, false] },
      { Q2: [true, false, false, false] },
      { Q3: [true, true, true, true] },
      { Q4: [true, true, true, true] },
    ],
    HCC: ["Q2", 8],
  };

  const playerDetails = [
    {
      license_no: 250,
      player: "Mayer F",
      no: 0,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P3", "Q1"], ["P", "Q2"], ["P", "Q3"], false, false],
    },
    {
      license_no: 252,
      player: "Manos J Jr",
      no: 3,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P", "Q4"], ["P", "Q3"], false, false, false],
    },
    {
      license_no: 253,
      player: "Jones M",
      no: 4,
      playerIn: [true, "Q1"],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 254,
      player: "Kent Q",
      no: 5,
      playerIn: [true, "Q2"],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 255,
      player: "Martinez C",
      no: 6,
      playerIn: [true, "Q2"],
      playerStart: false,
      fouls: [["P1", "Q3"], false, false, false, false],
    },
    {
      license_no: 256,
      player: "Lopez J (CAP)",
      no: 7,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P1", "Q2"], ["P", "Q4"], false, false, false],
    },
    {
      license_no: 257,
      player: "HEMEL D",
      no: 8,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 265,
      player: "Obradovic C",
      no: 9,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 266,
      player: "Aguilar V",
      no: 19,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 268,
      player: "Rimkus T",
      no: 12,
      playerIn: [true, "Q4"],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 300,
      player: "Perotti R",
      no: 15,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P1", "Q1"], ["P2", "Q2"], ["P", "Q2"], ["P2", "Q4"], false],
    },
    {
      license_no: 301,
      player: "Vidot A",
      no: 20,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P2", "Q1"], ["P2", "Q1"], ["P", "Q2"], false, false],
    },
  ];

  const playerDetails2 = [
    {
      license_no: 500,
      player: "Radonjic G",
      no: 4,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P1", "Q1"], ["P", "Q3"], false, false, false],
    },
    {
      license_no: 501,
      player: "Mantila P",
      no: 5,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 502,
      player: "Tanabe V",
      no: 6,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P", "Q2"], false, false, false, false],
    },
    {
      license_no: 503,
      player: "Puig J",
      no: 7,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 505,
      player: "Thron H",
      no: 8,
      playerIn: [true, "Q3"],
      playerStart: false,
      fouls: [["P2", "Q4"], false, false, false, false],
    },
    {
      license_no: 506,
      player: "Mitlech J",
      no: 9,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P2", "Q1"], ["P", "Q3"], ["P1", "Q4"], false, false],
    },
    {
      license_no: 700,
      player: "Marti C",
      no: 10,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 750,
      player: "Manjour R (CAP)",
      no: 11,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P", "Q1"], ["P2", "Q3"], ["P3", "Q4"], ["P2", "Q4"], false],
    },
    {
      license_no: 751,
      player: "Toteva I",
      no: 12,
      playerIn: [true, "Q2"],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
    {
      license_no: 766,
      player: "Lee A",
      no: 13,
      playerIn: [true, "Q2"],
      playerStart: false,
      fouls: [["P2", "Q1"], ["P2", "Q3"], false, false, false],
    },
    {
      license_no: 800,
      player: "Kem B",
      no: 14,
      playerIn: [true, true],
      playerStart: true,
      fouls: [["P", "Q1"], ["P", "Q2"], false, false, false],
    },
    {
      license_no: false,
      player: false,
      no: false,
      playerIn: [false, false],
      playerStart: false,
      fouls: [false, false, false, false, false],
    },
  ];

  const coachDetails = {
    headCoach: {
      no: "C001",
      name: "CANUT J",
      fouls: ["C0", false, false],
    },
    firstAssistantCoach: {
      no: "C80",
      name: "SERRAT A",
      fouls: [false, false, false],
    },
  };

  const coachDetails2 = {
    headCoach: {
      no: "C50",
      name: "Castro A",
      fouls: ["C0", false, false],
    },
    firstAssistantCoach: {
      no: "C111",
      name: "Aurienma J",
      fouls: [false, false, false],
    },
  };

  const signatures = {
    scorer: "ISOLA, D",
    assistantScorer: "ONNA, M",
    timer: "FERNANDEZ, P",
    shotClockOperator: "PATTON, M",
  };

  const scores = {
    teamAScore: [
      { key: 1, playerNumber: false, points: 0, totalScore: 0, quarter: "Q1" },
      { key: 2, playerNumber: 7, points: 2, totalScore: 2, quarter: "Q1" },
      { key: 3, playerNumber: false, points: 0, totalScore: 2, quarter: "Q1" },
      { key: 4, playerNumber: false, points: 0, totalScore: 2, quarter: "Q1" },
      { key: 5, playerNumber: 0, points: 3, totalScore: 5, quarter: "Q1" },
      { key: 6, playerNumber: false, points: 0, totalScore: 5, quarter: "Q1" },
      { key: 7, playerNumber: 3, points: 2, totalScore: 7, quarter: "Q1" },
      { key: 8, playerNumber: false, points: 0, totalScore: 7, quarter: "Q1" },
      { key: 9, playerNumber: false, points: 0, totalScore: 7, quarter: "Q1" },
      { key: 10, playerNumber: 0, points: 3, totalScore: 10, quarter: "Q1" },
      {
        key: 11,
        playerNumber: false,
        points: 0,
        totalScore: 10,
        quarter: "Q1",
      },
      { key: 12, playerNumber: 20, points: 2, totalScore: 12, quarter: "Q1" },
      {
        key: 13,
        playerNumber: false,
        points: 0,
        totalScore: 12,
        quarter: "Q1",
      },
      {
        key: 14,
        playerNumber: false,
        points: 0,
        totalScore: 12,
        quarter: "Q1",
      },
      { key: 15, playerNumber: 3, points: 3, totalScore: 15, quarter: "Q1" },
      {
        key: 16,
        playerNumber: false,
        points: 0,
        totalScore: 15,
        quarter: "Q1",
      },
      {
        key: 17,
        playerNumber: false,
        points: 0,
        totalScore: 15,
        quarter: "Q1",
      },
      { key: 18, playerNumber: 3, points: 3, totalScore: 18, quarter: "Q1" },
      {
        key: 19,
        playerNumber: false,
        points: 0,
        totalScore: 18,
        quarter: "Q1",
      },
      {
        key: 20,
        playerNumber: false,
        points: 0,
        totalScore: 18,
        quarter: "Q1",
      },
      { key: 21, playerNumber: 4, points: 3, totalScore: 21, quarter: "Q1" },
      {
        key: 22,
        playerNumber: false,
        points: 0,
        totalScore: 21,
        quarter: "Q1",
      },
      { key: 23, playerNumber: 15, points: 2, totalScore: 23, quarter: "Q1" },
      {
        key: 24,
        playerNumber: false,
        points: 0,
        totalScore: 23,
        quarter: "Q1",
      },
      { key: 25, playerNumber: 4, points: 2, totalScore: 25, quarter: "Q1" },
      {
        key: 26,
        playerNumber: false,
        points: 0,
        totalScore: 25,
        quarter: "Q2",
      },
      { key: 27, playerNumber: 6, points: 2, totalScore: 27, quarter: "Q2" },
      {
        key: 28,
        playerNumber: false,
        points: 0,
        totalScore: 27,
        quarter: "Q2",
      },
      { key: 29, playerNumber: 20, points: 2, totalScore: 29, quarter: "Q2" },
      {
        key: 30,
        playerNumber: false,
        points: 0,
        totalScore: 29,
        quarter: "Q2",
      },
      {
        key: 31,
        playerNumber: false,
        points: 0,
        totalScore: 29,
        quarter: "Q2",
      },
      { key: 32, playerNumber: 0, points: 3, totalScore: 32, quarter: "Q2" },
      {
        key: 33,
        playerNumber: false,
        points: 0,
        totalScore: 32,
        quarter: "Q2",
      },
      {
        key: 34,
        playerNumber: false,
        points: 0,
        totalScore: 32,
        quarter: "Q2",
      },
      { key: 35, playerNumber: 20, points: 3, totalScore: 35, quarter: "Q2" },
      {
        key: 36,
        playerNumber: false,
        points: 0,
        totalScore: 35,
        quarter: "Q2",
      },
      { key: 37, playerNumber: 20, points: 2, totalScore: 37, quarter: "Q2" },
      {
        key: 38,
        playerNumber: false,
        points: 0,
        totalScore: 37,
        quarter: "Q2",
      },
      { key: 39, playerNumber: 12, points: 2, totalScore: 39, quarter: "Q2" },
      { key: 40, playerNumber: 12, points: 1, totalScore: 40, quarter: "Q2" },
      { key: 41, playerNumber: 12, points: 1, totalScore: 41, quarter: "Q2" },
      {
        key: 42,
        playerNumber: false,
        points: 0,
        totalScore: 41,
        quarter: "Q3",
      },
      {
        key: 43,
        playerNumber: false,
        points: 0,
        totalScore: 41,
        quarter: "Q3",
      },
      { key: 44, playerNumber: 7, points: 3, totalScore: 44, quarter: "Q3" },
      { key: 45, playerNumber: 0, points: 1, totalScore: 45, quarter: "Q3" },
      {
        key: 46,
        playerNumber: false,
        points: 0,
        totalScore: 45,
        quarter: "Q3",
      },
      { key: 47, playerNumber: 3, points: 2, totalScore: 47, quarter: "Q3" },
      {
        key: 48,
        playerNumber: false,
        points: 0,
        totalScore: 47,
        quarter: "Q3",
      },
      { key: 49, playerNumber: 15, points: 2, totalScore: 49, quarter: "Q3" },
      {
        key: 50,
        playerNumber: false,
        points: 0,
        totalScore: 49,
        quarter: "Q3",
      },
      {
        key: 51,
        playerNumber: false,
        points: 0,
        totalScore: 49,
        quarter: "Q3",
      },
      { key: 52, playerNumber: 7, points: 3, totalScore: 52, quarter: "Q3" },
      {
        key: 53,
        playerNumber: false,
        points: 0,
        totalScore: 52,
        quarter: "Q3",
      },
      {
        key: 54,
        playerNumber: false,
        points: 0,
        totalScore: 52,
        quarter: "Q3",
      },
      { key: 55, playerNumber: 20, points: 3, totalScore: 55, quarter: "Q3" },
      {
        key: 56,
        playerNumber: false,
        points: 0,
        totalScore: 55,
        quarter: "Q3",
      },
      { key: 57, playerNumber: 0, points: 2, totalScore: 57, quarter: "Q3" },
      { key: 58, playerNumber: 6, points: 1, totalScore: 58, quarter: "Q3" },
      { key: 59, playerNumber: 6, points: 1, totalScore: 59, quarter: "Q3" },
      {
        key: 60,
        playerNumber: false,
        points: 0,
        totalScore: 59,
        quarter: "Q3",
      },
      { key: 61, playerNumber: 3, points: 2, totalScore: 61, quarter: "Q3" },
      {
        key: 62,
        playerNumber: false,
        points: 0,
        totalScore: 61,
        quarter: "Q3",
      },
      { key: 63, playerNumber: 6, points: 2, totalScore: 63, quarter: "Q3" },
      {
        key: 64,
        playerNumber: false,
        points: 0,
        totalScore: 63,
        quarter: "Q3",
      },
      { key: 65, playerNumber: 20, points: 2, totalScore: 65, quarter: "Q3" },
      {
        key: 66,
        playerNumber: false,
        points: 0,
        totalScore: 65,
        quarter: "Q4",
      },
      { key: 67, playerNumber: 0, points: 2, totalScore: 67, quarter: "Q4" },
      {
        key: 68,
        playerNumber: false,
        points: 0,
        totalScore: 67,
        quarter: "Q4",
      },
      {
        key: 69,
        playerNumber: false,
        points: 0,
        totalScore: 67,
        quarter: "Q4",
      },
      { key: 70, playerNumber: 7, points: 3, totalScore: 70, quarter: "Q4" },
      {
        key: 71,
        playerNumber: false,
        points: 0,
        totalScore: 70,
        quarter: "Q4",
      },
      { key: 72, playerNumber: 15, points: 2, totalScore: 72, quarter: "Q4" },
      {
        key: 73,
        playerNumber: false,
        points: 0,
        totalScore: 72,
        quarter: "Q4",
      },
      { key: 74, playerNumber: 7, points: 2, totalScore: 74, quarter: "Q4" },
      {
        key: 75,
        playerNumber: false,
        points: 0,
        totalScore: 74,
        quarter: "Q4",
      },
      { key: 76, playerNumber: 20, points: 2, totalScore: 76, quarter: "Q4" },
      { key: 77, playerNumber: 7, points: 1, totalScore: 77, quarter: "Q4" },
      { key: 78, playerNumber: 7, points: 1, totalScore: 78, quarter: "Q4" },
      {
        key: 79,
        playerNumber: false,
        points: 0,
        totalScore: 78,
        quarter: "Q4",
      },
      { key: 80, playerNumber: 3, points: 2, totalScore: 80, quarter: "Q4" },
      {
        key: 81,
        playerNumber: false,
        points: 0,
        totalScore: 80,
        quarter: "Q4",
      },
      { key: 82, playerNumber: 7, points: 2, totalScore: 82, quarter: "Q4" },
      { key: 83, playerNumber: 0, points: 1, totalScore: 83, quarter: "Q4" },
      { key: 84, playerNumber: 0, points: 1, totalScore: 84, quarter: "Q4" },
      {
        key: 85,
        playerNumber: false,
        points: 0,
        totalScore: 84,
        quarter: "Q4",
      },
      {
        key: 86,
        playerNumber: false,
        points: 0,
        totalScore: 84,
        quarter: "Q4",
      },
      { key: 87, playerNumber: 7, points: 3, totalScore: 87, quarter: "Q4" },
      {
        key: 88,
        playerNumber: false,
        points: 0,
        totalScore: 87,
        quarter: "Q4",
      },
      {
        key: 89,
        playerNumber: false,
        points: 0,
        totalScore: 87,
        quarter: "Q4",
      },
      { key: 90, playerNumber: 0, points: 3, totalScore: 90, quarter: "Q4" },
      {
        key: 91,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "Q4",
      },
      { key: 92, playerNumber: 20, points: 2, totalScore: 92, quarter: "Q4" },
      {
        key: 93,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "ENDGAME",
      },
      {
        key: 94,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 95,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 96,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 97,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 98,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 99,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 100,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 101,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 102,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 103,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 104,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 105,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 106,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 107,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 108,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 109,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 110,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 111,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 112,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 113,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 114,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 115,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 116,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 117,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 118,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 119,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 120,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 121,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 122,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 123,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 124,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 125,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 126,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 127,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 128,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 129,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 130,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 131,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 132,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 133,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 134,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 135,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 136,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 137,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 138,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 139,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 140,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 141,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 142,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 143,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 144,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 145,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 146,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 147,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 148,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 149,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 150,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 151,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 152,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 153,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 154,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 155,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 156,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 157,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 158,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 159,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
      {
        key: 160,
        playerNumber: false,
        points: 0,
        totalScore: 92,
        quarter: "END",
      },
    ],
    teamBScore: [
      { key: 1, playerNumber: false, points: 0, totalScore: 0, quarter: "Q1" },
      { key: 2, playerNumber: 6, points: 2, totalScore: 2, quarter: "Q1" },
      { key: 3, playerNumber: 6, points: 1, totalScore: 3, quarter: "Q1" },
      { key: 4, playerNumber: false, points: 0, totalScore: 3, quarter: "Q1" },
      { key: 5, playerNumber: 8, points: 2, totalScore: 5, quarter: "Q1" },
      { key: 6, playerNumber: 14, points: 1, totalScore: 6, quarter: "Q1" },
      { key: 7, playerNumber: 14, points: 1, totalScore: 7, quarter: "Q1" },
      { key: 8, playerNumber: 14, points: 1, totalScore: 8, quarter: "Q1" },
      { key: 9, playerNumber: false, points: 0, totalScore: 8, quarter: "Q1" },
      { key: 10, playerNumber: 4, points: 2, totalScore: 10, quarter: "Q1" },
      {
        key: 11,
        playerNumber: false,
        points: 0,
        totalScore: 10,
        quarter: "Q1",
      },
      { key: 12, playerNumber: 4, points: 2, totalScore: 12, quarter: "Q1" },
      {
        key: 13,
        playerNumber: false,
        points: 0,
        totalScore: 12,
        quarter: "Q1",
      },
      {
        key: 14,
        playerNumber: 14,
        points: 2,
        totalScore: 14,
        quarter: "Q1",
      },
      {
        key: 15,
        playerNumber: false,
        points: 0,
        totalScore: 14,
        quarter: "Q1",
      },
      {
        key: 16,
        playerNumber: false,
        points: 0,
        totalScore: 14,
        quarter: "Q1",
      },
      {
        key: 17,
        playerNumber: 14,
        points: 3,
        totalScore: 17,
        quarter: "Q1",
      },
      {
        key: 18,
        playerNumber: false,
        points: 0,
        totalScore: 17,
        quarter: "Q2",
      },
      {
        key: 19,
        playerNumber: 4,
        points: 2,
        totalScore: 19,
        quarter: "Q2",
      },
      {
        key: 20,
        playerNumber: false,
        points: 0,
        totalScore: 19,
        quarter: "Q2",
      },
      {
        key: 21,
        playerNumber: false,
        points: 0,
        totalScore: 19,
        quarter: "Q2",
      },
      {
        key: 22,
        playerNumber: 11,
        points: 3,
        totalScore: 22,
        quarter: "Q2",
      },
      {
        key: 23,
        playerNumber: false,
        points: 0,
        totalScore: 22,
        quarter: "Q2",
      },
      {
        key: 24,
        playerNumber: false,
        points: 0,
        totalScore: 22,
        quarter: "Q2",
      },
      { key: 25, playerNumber: 14, points: 3, totalScore: 25, quarter: "Q2" },
      {
        key: 26,
        playerNumber: false,
        points: 0,
        totalScore: 25,
        quarter: "Q2",
      },
      { key: 27, playerNumber: 14, points: 2, totalScore: 27, quarter: "Q2" },
      {
        key: 28,
        playerNumber: false,
        points: 0,
        totalScore: 27,
        quarter: "Q2",
      },
      { key: 29, playerNumber: 8, points: 2, totalScore: 29, quarter: "Q2" },
      {
        key: 30,
        playerNumber: false,
        points: 0,
        totalScore: 29,
        quarter: "Q2",
      },
      {
        key: 31,
        playerNumber: 11,
        points: 2,
        totalScore: 31,
        quarter: "Q2",
      },
      {
        key: 32,
        playerNumber: false,
        points: 0,
        totalScore: 31,
        quarter: "Q2",
      },
      {
        key: 33,
        playerNumber: false,
        points: 0,
        totalScore: 31,
        quarter: "Q2",
      },
      {
        key: 34,
        playerNumber: 11,
        points: 3,
        totalScore: 34,
        quarter: "Q2",
      },
      {
        key: 35,
        playerNumber: false,
        points: 0,
        totalScore: 34,
        quarter: "Q2",
      },
      {
        key: 36,
        playerNumber: false,
        points: 0,
        totalScore: 34,
        quarter: "Q2",
      },
      { key: 37, playerNumber: 11, points: 3, totalScore: 37, quarter: "Q2" },
      {
        key: 38,
        playerNumber: 11,
        points: 1,
        totalScore: 38,
        quarter: "Q2",
      },
      {
        key: 39,
        playerNumber: false,
        points: 0,
        totalScore: 38,
        quarter: "Q2",
      },
      {
        key: 40,
        playerNumber: false,
        points: 0,
        totalScore: 38,
        quarter: "Q2",
      },
      { key: 41, playerNumber: 12, points: 3, totalScore: 41, quarter: "Q2" },
      {
        key: 42,
        playerNumber: false,
        points: 0,
        totalScore: 41,
        quarter: "Q2",
      },
      {
        key: 43,
        playerNumber: false,
        points: 0,
        totalScore: 41,
        quarter: "Q2",
      },
      { key: 44, playerNumber: 13, points: 3, totalScore: 44, quarter: "Q2" },
      {
        key: 45,
        playerNumber: false,
        points: 0,
        totalScore: 44,
        quarter: "Q3",
      },
      {
        key: 46,
        playerNumber: 14,
        points: 2,
        totalScore: 46,
        quarter: "Q3",
      },
      {
        key: 47,
        playerNumber: false,
        points: 0,
        totalScore: 46,
        quarter: "Q3",
      },
      {
        key: 48,
        playerNumber: 11,
        points: 2,
        totalScore: 48,
        quarter: "Q3",
      },
      {
        key: 49,
        playerNumber: false,
        points: 0,
        totalScore: 48,
        quarter: "Q3",
      },
      {
        key: 50,
        playerNumber: 11,
        points: 2,
        totalScore: 50,
        quarter: "Q3",
      },
      {
        key: 51,
        playerNumber: false,
        points: 0,
        totalScore: 50,
        quarter: "Q3",
      },
      { key: 52, playerNumber: 9, points: 2, totalScore: 52, quarter: "Q3" },
      {
        key: 53,
        playerNumber: false,
        points: 0,
        totalScore: 52,
        quarter: "Q3",
      },
      {
        key: 54,
        playerNumber: false,
        points: 0,
        totalScore: 52,
        quarter: "Q3",
      },
      { key: 55, playerNumber: 11, points: 3, totalScore: 55, quarter: "Q3" },
      {
        key: 56,
        playerNumber: false,
        points: 0,
        totalScore: 55,
        quarter: "Q3",
      },
      { key: 57, playerNumber: 11, points: 2, totalScore: 57, quarter: "Q3" },
      {
        key: 58,
        playerNumber: false,
        points: 0,
        totalScore: 57,
        quarter: "Q3",
      },
      { key: 59, playerNumber: 5, points: 2, totalScore: 59, quarter: "Q3" },
      {
        key: 60,
        playerNumber: 5,
        points: 1,
        totalScore: 60,
        quarter: "Q3",
      },
      {
        key: 61,
        playerNumber: false,
        points: 0,
        totalScore: 60,
        quarter: "Q3",
      },
      {
        key: 62,
        playerNumber: false,
        points: 0,
        totalScore: 60,
        quarter: "Q3",
      },
      { key: 63, playerNumber: 9, points: 3, totalScore: 63, quarter: "Q3" },
      {
        key: 64,
        playerNumber: false,
        points: 0,
        totalScore: 63,
        quarter: "Q3",
      },
      { key: 65, playerNumber: 11, points: 2, totalScore: 65, quarter: "Q3" },
      {
        key: 66,
        playerNumber: false,
        points: 0,
        totalScore: 65,
        quarter: "Q3",
      },
      {
        key: 67,
        playerNumber: false,
        points: 0,
        totalScore: 65,
        quarter: "Q3",
      },
      {
        key: 68,
        playerNumber: 13,
        points: 3,
        totalScore: 68,
        quarter: "Q3",
      },
      {
        key: 69,
        playerNumber: false,
        points: 0,
        totalScore: 68,
        quarter: "Q3",
      },
      { key: 70, playerNumber: 9, points: 2, totalScore: 70, quarter: "Q3" },
      {
        key: 71,
        playerNumber: 9,
        points: 1,
        totalScore: 71,
        quarter: "Q3",
      },
      {
        key: 72,
        playerNumber: false,
        points: 0,
        totalScore: 71,
        quarter: "Q3",
      },
      {
        key: 73,
        playerNumber: false,
        points: 0,
        totalScore: 71,
        quarter: "Q3",
      },
      { key: 74, playerNumber: 11, points: 3, totalScore: 74, quarter: "Q3" },
      {
        key: 75,
        playerNumber: false,
        points: 0,
        totalScore: 74,
        quarter: "Q4",
      },
      {
        key: 76,
        playerNumber: false,
        points: 0,
        totalScore: 74,
        quarter: "Q4",
      },
      { key: 77, playerNumber: 9, points: 3, totalScore: 77, quarter: "Q4" },
      {
        key: 78,
        playerNumber: false,
        points: 0,
        totalScore: 77,
        quarter: "Q4",
      },
      {
        key: 79,
        playerNumber: 6,
        points: 2,
        totalScore: 79,
        quarter: "Q4",
      },
      { key: 80, playerNumber: 14, points: 1, totalScore: 80, quarter: "Q4" },
      {
        key: 81,
        playerNumber: 14,
        points: 1,
        totalScore: 81,
        quarter: "Q4",
      },
      {
        key: 82,
        playerNumber: false,
        points: 0,
        totalScore: 81,
        quarter: "Q4",
      },
      {
        key: 83,
        playerNumber: false,
        points: 0,
        totalScore: 81,
        quarter: "Q4",
      },
      { key: 84, playerNumber: 11, points: 3, totalScore: 84, quarter: "Q4" },
      {
        key: 85,
        playerNumber: false,
        points: 0,
        totalScore: 84,
        quarter: "Q4",
      },
      {
        key: 86,
        playerNumber: 9,
        points: 2,
        totalScore: 86,
        quarter: "Q4",
      },
      {
        key: 87,
        playerNumber: false,
        points: 0,
        totalScore: 86,
        quarter: "Q4",
      },
      {
        key: 88,
        playerNumber: 14,
        points: 2,
        totalScore: 88,
        quarter: "Q4",
      },
      {
        key: 89,
        playerNumber: false,
        points: 0,
        totalScore: 88,
        quarter: "Q4",
      },
      { key: 90, playerNumber: 6, points: 2, totalScore: 90, quarter: "Q4" },
      {
        key: 91,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "ENDGAME",
      },
      {
        key: 92,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 93,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 94,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 95,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 96,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 97,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 98,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 99,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 100,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 101,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 102,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 103,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 104,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 105,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 106,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 107,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 108,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 109,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 110,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 111,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 112,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 113,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 114,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 115,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 116,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 117,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 118,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 119,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 120,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 121,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 122,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 123,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 124,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 125,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 126,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 127,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 128,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 129,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 130,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 131,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 132,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 133,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 134,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 135,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 136,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 137,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 138,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 139,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 140,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 141,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 142,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 143,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 144,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 145,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 146,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 147,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 148,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 149,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 150,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 151,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 152,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 153,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 154,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 155,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 156,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 157,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 158,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 159,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
      {
        key: 160,
        playerNumber: false,
        points: 0,
        totalScore: 90,
        quarter: "END",
      },
    ],
  };

  const finalStats = {
    quarter1: { teamA: 25, teamB: 17 },
    quarter2: { teamA: 16, teamB: 27 },
    quarter3: { teamA: 24, teamB: 30 },
    quarter4: { teamA: 27, teamB: 16 },
    overtime: { teamA: false, teamB: false },
    finalScore: { teamA: 92, teamB: 90 },
    winningTeam: "BC MIES",
    gameEndTime: "22:05",
  };

  return (
    <>
      <div className="pl-2 pr-2 ">
        <ScoresheetHeader gameDetails={gameDetails} />
        <div className="border-2 border-black mt-4 mb-4">
          <GameDetails gameDetails={gameDetails} />
          <div className="flex justify-center w-full">
            <div className="w-1/2 border-r-2 border-black flex flex-col items-center">
              <TeamStats
                team="A"
                teamName={gameDetails.teamA}
                teamDetails={team1Details}
              />

              <Players
                playerDetails={playerDetails}
                coachDetails={coachDetails}
              />
              <TeamStats
                team="B"
                teamName={gameDetails.teamB}
                teamDetails={team2Details}
              />
              <Players
                playerDetails={playerDetails2}
                coachDetails={coachDetails2}
              />
              <Signatures signatures={signatures} />
            </div>
            <div className="w-1/2 flex flex-col items-center">
              <RunningScore scores={scores} />

              <Scores finalStats={finalStats} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
